"use client";
import Link from "next/link";
import { useMemo, useState } from "react";
import { collectionNames, navigation } from "@/data/site";
export type Product = { id: number; title: string; handle: string; images: { src: string; alt?: string }[]; variants: { price: string; compare_at_price?: string | null }[] };
const money = (v?: string | null) => v ? `₹${Number(v).toLocaleString("en-IN")}` : "";
export function Header() { const [open,setOpen]=useState(false); return <><div className="announcement">FREE SHIPPING ON PREPAID ORDERS &nbsp; • &nbsp; EXTRA 5% OFF</div><header className="site-header"><button className="mobile-toggle" onClick={()=>setOpen(!open)}>☰</button><Link className="logo" href="/">GULABO <span>JAIPUR</span></Link><nav className={open?"nav open":"nav"}>{navigation.map(x=><Link href={x.href} key={x.href}>{x.label}</Link>)}</nav><div className="header-actions"><button>⌕</button><button>♡</button><button>Bag (0)</button></div></header></> }
export function CollectionPage({slug,products}:{slug:string;products:Product[]}) { const [sort,setSort]=useState("Featured"); const [hearts,setHearts]=useState<number[]>([]); const items=useMemo(()=>[...products].sort((a,b)=>sort==="Price: Low to High"?Number(a.variants[0]?.price)-Number(b.variants[0]?.price):sort==="Price: High to Low"?Number(b.variants[0]?.price)-Number(a.variants[0]?.price):0),[products,sort]); const title=collectionNames[slug]; return <><Header/><main><section className="collection-hero"><p>Home / Collections / {title}</p><h1>{title}</h1></section><section className="catalog-toolbar"><button>Filter & Sort　☷</button><p>{products.length} products</p><label>Sort by <select value={sort} onChange={e=>setSort(e.target.value)}><option>Featured</option><option>Price: Low to High</option><option>Price: High to Low</option></select></label></section><section className="product-grid">{items.map(p=><article className="product-card" key={p.id}><div className="product-media"><Link href={`/products/${p.handle}`}><img src={p.images[0]?.src} alt={p.images[0]?.alt||p.title}/>{p.images[1]&&<img className="hover-image" src={p.images[1].src} alt=""/>}</Link><button className="heart" onClick={()=>setHearts(x=>x.includes(p.id)?x.filter(id=>id!==p.id):[...x,p.id])}>{hearts.includes(p.id)?"♥":"♡"}</button><button className="quick">Add to Bag</button></div><div className="product-info"><h2>{p.title}</h2><p>{money(p.variants[0]?.price)} {p.variants[0]?.compare_at_price&&<del>{money(p.variants[0].compare_at_price)}</del>}</p></div></article>)}</section></main><Footer/></> }
export function Footer(){return <footer><div className="footer-brand"><div className="logo">GULABO <span>JAIPUR</span></div><p>Modern heirlooms, thoughtfully made in Jaipur.</p></div><div><h3>SHOP</h3>{navigation.slice(0,5).map(x=><Link href={x.href} key={x.href}>{x.label}</Link>)}</div><div><h3>ABOUT</h3><a>Our Story</a><a>Stores</a><a>Contact</a></div><div><h3>NEWSLETTER</h3><p>Sign up for first access to new arrivals.</p><div className="email">Email address <button>→</button></div></div></footer>}
